export const userConstants = {
    LOGIN_USER_REQUEST: 'LOGIN_USER',
    USER_EXISTS: 'USER_EXISTS',
    USER_DOES_NOT_EXISTS: 'USER_DOES_NOT_EXISTS',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    REGISTER_SUCCESS: 'REGISTER_USER',
    REGISTER_FAILED: 'REGISTER_FAILED'


}