name: build and create docker image
on:
  push:
    branches:
      - main

jobs:
  compile_and_test:
      uses: ./.github/workflows/feature_pr.yml
  
  build_package:
      needs: compile_and_test
      runs-on: ubuntu-latest
      steps:
        - name: building package 
          run: npm run build

        - name: Build & push Docker image
          uses: mr-smithers-excellent/docker-build-push@v5
          with:
            image: alirezaeiji151379/asd_frontend
            tags: beta
            registry: docker.io
            dockerfile: ../../Dockerfile
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
